"""Sheru stress test — routes many utterances through the REAL router + local 4B (actions mocked so nothing
happens for real) and reports where routing succeeds and fails.

Run:  uv run python tests/stress_test.py            # grammar + local-LLM routing
      uv run python tests/stress_test.py --no-llm   # grammar only (fast, deterministic)

Merges data/stress_cases.json (generated by the case-gen workflow) with the built-in corpus below.
"""
from __future__ import annotations

import json
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

# ---- built-in corpus: (utterance, expected_kind, arg_substring_or_None) --------------------------------
CORPUS = [
    # apps
    ("open spotify", "open_app", "spotify"), ("open the zen browser", "open_app", "zen"),
    ("launch discord", "open_app", "discord"), ("quit spotify", "quit_app", "spotify"),
    ("switch to obsidian", "switch_app", "obsidian"), ("open settings", "open_app", "System Settings"),
    ("open the terminal", "open_app", "ghostty"), ("open whatsapp", "open_app", "whatsapp"),
    # web / search / images
    ("search for best ramen in delhi", "search", "ramen"),
    ("search for m5 macbook reviews on google", "search", "macbook"),
    ("show me pictures of tigers", "images", "tigers"),
    ("show me some pictures of the taj mahal", "images", "taj mahal"),
    ("use google", "set_engine", None), ("use duckduckgo", "set_engine", None),
    ("go to github.com", "url", "github"), ("open youtube.com", "url", "youtube"),
    ("search for the best momos and summarize", "claude", None),
    # current-info -> Claude
    ("what's the weather at my location", "claude", None), ("what's the weather in gangtok", "claude", None),
    ("summarize the news about ai", "claude", None), ("summarize the results", "chat", None),  # no prior search
    # messages
    ("message bob that i won't make his nightout because i'm sick", "message", None),
    ("text mom saying i'll be home late", "message", None),
    ("whatsapp raj that the meeting moved to 5", "message", None),
    # system / media / timers
    ("volume 40", "volume", None), ("turn it up", "volume", None), ("mute", "mute", None),
    ("pause", "media", None), ("next song", "media", None), ("play music", "media", None),
    ("play choo lo on spotify", "play_song", "choo"), ("play sanam re", "play_song", "sanam"),
    ("set a timer for five minutes", "timer", None), ("timer 30 seconds", "timer", None),
    ("what time is it", "time", None), ("what's on my clipboard", "clipboard", None),
    # memory / personal
    ("remember i prefer tea over coffee", "remember", None),
    ("remember my college profile is called college", "remember", None),
    ("set my location to gangtok", "set_location", None),
    # chat / edge
    ("how are you", "chat", None), ("tell me a fun fact about octopuses", "chat", None),
    ("you're my companion not just a voice assistant", "chat", None),
    ("stop", "stop", None), ("cancel", "stop", None),
    ("ask claude to summarize my downloads folder", "claude", None),
    ("write a python script to rename my photos", "claude", None),
    # reminders (new capability)
    ("remind me to call mom in 10 minutes", "remind", None),
    ("remind me to take my medicine at 9 pm", "remind", None),
    ("remind me to submit the report at 5", "remind", None),
    ("remind me to drink water in an hour", "remind", None),
    # phrasing gaps
    ("what did i copy", "clipboard", None),
    ("do you have the time", "time", None),
    ("i just moved to gangtok", "set_location", None),
    ("i'm now in delhi", "set_location", None),
    # corrections (re-route)
    ("actually open spotify", "open_app", "spotify"),
    ("no i meant search for pizza recipes", "search", "pizza"),
    ("scratch that play some music", "media", None),
    # idioms that should NOT over-trigger
    ("i live in the moment", "chat", None),
    ("remember when we went to goa", "chat", None),
]

# expected kinds that all legitimately go to Claude (handoff)
CLAUDE_KINDS = {"claude", "weather", "summarize", "ask_claude", "search_summarize", "current"}
ALIAS = {"set_volume": "volume", "recall": "chat"}


def install_mocks():
    """Patch every action to return a parseable marker so we can see WHERE routing sent the command."""
    import sheru.router as R

    def mk(kind):
        return lambda *a, **k: f"[[{kind}:{(str(a[0]) if a else '')}]]"

    _resolve = R.apps.resolve
    R.apps.open_app = lambda n: f"[[open_app:{_resolve(n) or n}]]"
    R.apps.quit_app = lambda n: f"[[quit_app:{_resolve(n) or n}]]"
    R.apps.switch_to = lambda n: f"[[switch_app:{_resolve(n) or n}]]"
    R.web.search = lambda q, e=None: f"[[search:{q}]]"; R.web.image_search = lambda q, e=None: f"[[images:{q}]]"
    R.web.set_search_engine = mk("set_engine"); R.web.open_url = mk("url"); R.web.switch_profile = mk("switch_app")
    R.web.last_query = lambda: None
    R.system.set_volume = mk("volume"); R.system.change_volume = lambda d: f"[[volume:{d}]]"
    R.system.mute = mk("mute"); R.system.media = mk("media"); R.system.now = lambda: "[[time:]]"
    R.system.clipboard = lambda: "clip"; R.system.set_timer = lambda s, cb, label="t": f"[[timer:{s}]]"
    R.music.play_song = mk("play_song")
    R.weather.fetch = lambda c: None       # force the Claude-fallback path in tests (no live network call)
    R.files.make = lambda r: f"[[fs:{r}]]"; R.files.open_terminal = lambda w=None: "[[terminal:]]"
    R.location.localize = lambda t: t; R.location.describe = lambda: "Ravangla, Sikkim"
    import sheru.config as _C; _C.update_profile = lambda *a, **k: None      # set_location: no real write
    import sheru.reminders as _REM; _REM.schedule = lambda *a, **k: None     # remind: no real timer/persist


class FakeMem:
    def remember(self, t):
        return f"[[remember:{t}]]"
    def context_block(self, q):
        return ""


def classify(res):
    if getattr(res, "draft", None):
        return "message", None
    if res.handoff:
        return "claude", res.handoff
    sp = res.speech or ""
    m = re.match(r"\[\[(\w+):(.*?)\]\]", sp)
    if m:
        return m.group(1), m.group(2)
    if "as your location" in sp:
        return "set_location", None
    if sp.startswith("Clipboard "):
        return "clipboard", None
    if sp.startswith(("Okay, I'll remind", "When should I remind")):
        return "remind", None
    if sp.strip() == "" and getattr(res, "tier", 0) == 0:
        return "stop", None
    if sp.strip() in ("", "Yes?"):
        return "chat", None
    return "chat", sp


def load_cases():
    cases = [{"utterance": u, "kind": k, "arg_contains": a, "adversarial": False} for u, k, a in CORPUS]
    extra = ROOT / "data" / "stress_cases.json"
    if extra.exists():
        try:
            gen = json.loads(extra.read_text())
            cases += gen if isinstance(gen, list) else gen.get("cases", [])
        except Exception as e:
            print("could not load generated cases:", e)
    return cases


def main():
    use_llm = "--no-llm" not in sys.argv
    from sheru.router import Router
    install_mocks()
    llm = None
    if use_llm:
        from sheru.llm_local import LocalLLM
        print("loading local 4B (for fall-through routing)…")
        llm = LocalLLM().load()
    router = Router(llm=llm, memory=FakeMem())

    cases = load_cases()
    print(f"\nRunning {len(cases)} cases (llm={'on' if use_llm else 'off'})\n" + "=" * 70)
    by_kind = defaultdict(lambda: [0, 0])   # expected_kind -> [pass, total]
    fails = []
    for c in cases:
        u, exp = c["utterance"], c.get("kind", "?")
        try:
            res = router.route(u)
            got, arg = classify(res)
        except Exception as e:
            got, arg = "ERROR", repr(e)
        exp_n = "claude" if exp in CLAUDE_KINDS else ALIAS.get(exp, exp)
        got_n = "claude" if got in CLAUDE_KINDS else ALIAS.get(got, got)
        ok = (exp_n == got_n)
        # arg check (soft) — skip for app kinds (the resolver renames: music->Spotify)
        sub = c.get("arg_contains")
        if ok and sub and arg is not None and exp not in ("open_app","quit_app","switch_app") and sub.lower() not in str(arg).lower():
            ok = False
            got = f"{got}(arg!≈{sub})"
        by_kind[exp][0] += int(ok); by_kind[exp][1] += 1
        if not ok:
            fails.append((u, exp, got, "adv" if c.get("adversarial") else ""))

    total_ok = sum(p for p, _ in by_kind.values()); total = sum(t for _, t in by_kind.values())
    print(f"\nOVERALL: {total_ok}/{total} ({100*total_ok//max(total,1)}%) routed as expected\n")
    print("Per-capability:")
    for kind in sorted(by_kind):
        p, t = by_kind[kind]
        bar = "✓" if p == t else ("~" if p else "✗")
        print(f"  {bar} {kind:16} {p}/{t}")
    if fails:
        print(f"\nFAILURES ({len(fails)}) — utterance | expected -> got:")
        for u, exp, got, adv in fails:
            print(f"  [{adv:3}] {u[:48]:48} | {exp} -> {got}")
    print("\n(actions were mocked — nothing ran for real. 'claude' = would delegate; 'chat' = local answer.)")


if __name__ == "__main__":
    main()
